include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_null_aware_expression: ignore
    unnecessary_null_comparison: ignore
    deprecated_member_use: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    unnecessary_import: ignore
    dead_code: ignore

linter:
  rules:
    # Temporarily relax noisy rules to achieve a clean analyze run
    avoid_print: false
    use_build_context_synchronously: false
    non_constant_identifier_names: false
    constant_identifier_names: false
    avoid_types_as_parameter_names: false