name: mindload
description: "Mindload - AI Study Companion for focused learning with flashcards, quizzes, and ultra study mode with binaural beats"
publish_to: "none"
version: 1.0.0+15

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Firebase - Stable Compatible Versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  cloud_functions: ^4.6.0
  firebase_app_check: ^0.2.1+18
  firebase_remote_config: ^4.3.8
  
  # UI & Fonts
  google_fonts: ^6.2.1
  
  # Authentication
  local_auth: ^2.3.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  
  # File & Data
  shared_preferences: ^2.3.3
  file_picker: ^10.3.1
  path_provider: ^2.1.4
  syncfusion_flutter_pdf: ^30.2.7
  archive: ^4.0.7
  xml: ^6.5.0
  
  # Networking
  url_launcher: ^6.3.1
  http: ^1.2.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  uuid: ^4.1.0
  
  # Notifications - Stable Versions
  flutter_local_notifications: ^19.4.1
  # Replace flutter_native_timezone (package-level manifest causes AGP errors) with flutter_timezone
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  # iOS Live Activities (ActivityKit) plugin
  live_activities: ^2.3.0
  
  # Audio & Video
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  video_player: ^2.8.1
  
  # In-App Purchases - StoreKit 2 Support
  in_app_purchase: ^3.1.11
  in_app_purchase_storekit: ^0.4.4
  in_app_purchase_android: ^0.4.0+3
  
  # Internationalization
  intl: ^0.20.2
  image_picker: ^1.2.0
  image: ^4.5.4
  share_plus: ^11.1.0
  
  # Charts & Data Visualization
  # fl_chart: ^0.68.0  # Removed - using custom implementations instead

dependency_overrides:
  # Work around Android build issues in latest sqflite_android by pinning to a compatible version
  sqflite_android: 2.4.1
  # Update transitive packages to latest versions
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  _fe_analyzer_shared: ^88.0.0
  analyzer: ^8.1.1
  dart_style: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    # Optimized asset loading - now includes compressed audio
    - assets/audio/
    - assets/images/
    - assets/phrases/notification_phrases.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/brain_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/brain_logo.png"
    background_color: "#000000"
    theme_color: "#1565C0"
  windows:
    generate: true
    image_path: "assets/icon/brain_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/brain_logo.png"
