// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android; // Use Android configuration for Linux compatibility
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5W9fk1gE987PBexYcone_QVapotA_kHM',
    appId: '1:884947669542:web:db39decdf401cc5ba74ce7',
    messagingSenderId: '884947669542',
    projectId: 'lca5kr3efmasxydmsi1rvyjoizifj4',
    authDomain: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebaseapp.com',
    storageBucket: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebasestorage.app',
    measurementId: 'G-S8FXSS0QKM',
    databaseURL:
        'https://lca5kr3efmasxydmsi1rvyjoizifj4-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEAnhPEafjt-dXubYp6y61xrQ2ynA2cg',
    appId: '1:884947669542:android:3a905516036f560ba74ce7',
    messagingSenderId: '884947669542',
    projectId: 'lca5kr3efmasxydmsi1rvyjoizifj4',
    storageBucket: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwmw8qPpAAWTTwNIpFHIwwSioYRX_UMk',
    appId: '1:884947669542:ios:a0f6587d65102118a74ce7',
    messagingSenderId: '884947669542',
    projectId: 'lca5kr3efmasxydmsi1rvyjoizifj4',
    storageBucket: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebasestorage.app',
    iosBundleId: 'com.MindLoad.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEAnhPEafjt-dXubYp6y61xrQ2ynA2cg',
    appId: '1:884947669542:macos:db39decdf401cc5ba74ce7',
    messagingSenderId: '884947669542',
    projectId: 'lca5kr3efmasxydmsi1rvyjoizifj4',
    storageBucket: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebasestorage.app',
    iosBundleId: 'com.MindLoad.ios',
    databaseURL:
        'https://lca5kr3efmasxydmsi1rvyjoizifj4-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSEAnhPEafjt-dXubYp6y61xrQ2ynA2cg',
    appId: '1:884947669542:windows:db39decdf401cc5ba74ce7',
    messagingSenderId: '884947669542',
    projectId: 'lca5kr3efmasxydmsi1rvyjoizifj4',
    storageBucket: 'lca5kr3efmasxydmsi1rvyjoizifj4.firebasestorage.app',
    databaseURL:
        'https://lca5kr3efmasxydmsi1rvyjoizifj4-default-rtdb.firebaseio.com',
  );
}
